import {
  SiReact,
  SiNodedotjs,
  SiExpress,
  SiMongodb,
  SiStripe,
  SiVuedotjs,
  SiFirebase,
  SiTailwindcss,
  SiRedux,
  SiPostgresql,
  SiChartdotjs,
  SiPython,
  SiTensorflow,
  SiFlask,
  SiSocketdotio,
  SiSolidity,
  SiEthereum,
} from "react-icons/si";
import { TbApi } from "react-icons/tb";

export const technologies = [
  { id: "react", Icon: SiReact, name: "React" },
  { id: "nodejs", Icon: SiNodedotjs, name: "Node.js" },
  { id: "express", Icon: SiExpress, name: "Express" },
  { id: "mongodb", Icon: SiMongodb, name: "MongoDB" },
  { id: "stripe", Icon: SiStripe, name: "Stripe" },
  { id: "vuejs", Icon: SiVuedotjs, name: "Vue.js" },
  { id: "firebase", Icon: SiFirebase, name: "Firebase" },
  { id: "tailwindcss", Icon: SiTailwindcss, name: "Tailwind CSS" },
  { id: "redux", Icon: SiRedux, name: "Redux" },
  { id: "openweathermap", Icon: TbApi, name: "OpenWeatherMap API" },
  { id: "postgresql", Icon: SiPostgresql, name: "PostgreSQL" },
  { id: "chartjs", Icon: SiChartdotjs, name: "Chart.js" },
  { id: "python", Icon: SiPython, name: "Python" },
  { id: "tensorflow", Icon: SiTensorflow, name: "TensorFlow" },
  { id: "flask", Icon: SiFlask, name: "Flask" },
  { id: "socketio", Icon: SiSocketdotio, name: "Socket.io" },
  { id: "solidity", Icon: SiSolidity, name: "Solidity" },
  { id: "ethereum", Icon: SiEthereum, name: "Ethereum" },
];
